.PHONY: clean All

All:
	@echo "----------Building project:[ Inheritance - Debug ]----------"
	@cd "Inheritance" && "$(MAKE)" -f  "Inheritance.mk"
clean:
	@echo "----------Cleaning project:[ Inheritance - Debug ]----------"
	@cd "Inheritance" && "$(MAKE)" -f  "Inheritance.mk" clean
